### ISSUE TITLE
APK: Add scroll to first unread

### ISSUE THREAD

**Issue by ichpen** [ForumApps/forumappsandroid#18]
Very needed for threads with large number of posts. Currently no way of scrolling to first unread or bottom

**Comment by prathmeshranaut** [comment]
Made an update that scrolls itself to the last unread thread. Since we don’t have pagination yet I think this is a workaround. But in future the user will be directly jumped to the last unread thread.

**Comment by ichpen** [comment]
Last unread post you mean?

**Comment by prathmeshranaut** [comment]
Sorry, yes. Last unread post.
