### ISSUE TITLE
Thread stats not updated

### ISSUE THREAD

**Issue by ichpen** [ForumApps/forumappsandroid#9]
New thread, reply within a min or two, go back to forum view, reply/view stats not updated.

**Comment by ichpen** [comment]
This is somewhat intermittent behaviour I've noticed.

**Comment by prathmeshranaut** [comment]
Yes, this behavior is with all the threads and conversations.

**Comment by prathmeshranaut** [comment]
To save bandwidth and reduce load on the server, this is intended. However we will add a swipe to refresh which you can use to refresh the stats.
